### PR TITLE
remove duplicate import

### PR DESCRIPTION
**Pull request by sify21**
ApacheTomcatDataSource is imported twice

### CODE REVIEW

**Comment by sbs2001** [comment]
@sify21  thanks :) could you fix the dco so I can merge this ?

**Comment by sbs2001** [comment]
@sify21  ping

**Comment by sify21** [comment]
Sorry, I followed the steps to fix the dco, it seems not working

**Comment by sbs2001** [comment]
@sify21  make a new pr then. While doing the commit remember to use `git commit -s -m "commit message"`  syntax

**Pull request closed without merging**
