### PR TITLE
Make docs RTD compatible

### PR DESCRIPTION
**Pull request by AyanSinhaMahapatra**
Partially adresses #498

### CODE REVIEW

**Comment by AyanSinhaMahapatra** [comment]
I activated my fork of vulnerablecode at RTD, see [here](https://vulnerablecode-fork-ayan.readthedocs.io/en/latest/).

Seems to be working fine. Just activating should host successfully.

**Review by pombredanne — APPROVED** [review]
Awesome! :bow:

**Review by sbs2001 — APPROVED** [review]
Thanks!

**Comment by pombredanne** [comment]
The test failure is not related to docs... merging then!

**Pull request merged**
