### PR TITLE
Stop using drf-spectacular

### PR DESCRIPTION
**Pull request by sbs2001**
- Use Redoc instead of swagger
- Don't rely on CDN
- Fix docs for bulk_search API

Fixes https://github.com/nexB/vulnerablecode/issues/454 , https://github.com/nexB/vulnerablecode/issues/446

Signed-off-by: Shivam Sandbhor <shivam.sandbhor@gmail.com>

### CODE REVIEW

**Comment by pombredanne** [comment]
Just curious: what's the rationale for selecting redoc?

**Comment by pombredanne** [comment]
Redoc comes from :
- Version: "2.0.0-rc.56"
- Repo: https://github.com/Redocly/redoc
- it was downloaded with npm install redoc and the file from the node_modules were carried over


To get the code in a script, first get the JSON api at https://registry.npmjs.org/redoc
Then under `versions/dist` get the dist tarball at https://registry.npmjs.org/redoc/-/redoc-2.0.0-rc.56.tgz

This is overall a messy provenance and therefore license.

**Comment by pombredanne** [comment]
This could be a better source than the npm package https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js and this is also messy license.

**Comment by Hritik14** [comment]
Steps to take about licensing after merging this PR: https://github.com/nexB/vulnerablecode/issues/549

**Comment by tfranzel** [comment]
Hi,

I watched this a bit from the sidelines and I have to admit I'm a bit puzzled. Maybe I have been too imprecise in [my statements](https://github.com/tfranzel/drf-spectacular/issues/389#issuecomment-843384777).

> nobody is forcing you to use the CDN. if you are so inclined, you are free to change those settings and host your swagger-ui build yourself. that is exactly the reason why the setting is there.

You then partially did what I recommended; ingesting the distribution builds into your static folder. So far so good. However, instead of simply setting `'REDOC_DIST': '//cdn.jsdelivr.net/npm/redoc@next'` to `'REDOC_DIST': 'YOUR_STATIC_ROOT/api_doc'`, you went ahead removed `spectacular` altogether and hard-coded the schema. You could call that throwing out the baby with the bath water.

The whole point of spectacular is not having stale, outdated hard-coded API specifications. This kind of defeats the purpose of the whole thing but I digress. But on a lighter note, we just added your request: https://github.com/tfranzel/drf-spectacular#self-contained-ui-installation

This installs https://github.com/tfranzel/drf-spectacular-sidecar, which is an optional package containing all those assets. The package sources from jsdelivr and releases a PyPi package containing those static files. Basically what you did in this PR. Just some food for thought. Have a good day!

**Comment by pombredanne** [comment]
@tfranzel FYI, I am working to reinstate drf-spectacular with swagger which is much better than a plain redoc and this before we are effectively going public :)
Thank you ++ for the sidecar publication!
You rock

**Pull request merged**
