### PR TITLE
Added faq section

### LINKED ISSUE #282: Add FAQ section in docs
Add a FAQ section in docs with a question related to importing data while setting up VulnerableCode.

### PR DESCRIPTION
**Pull request by tushar912**
Fixes #282 .
## Description
I have added FAQ section in doc with a question related to importing data while setting up.
## Screenshot
rst

### CODE REVIEW

**Comment by sbs2001** [comment]
@tushar912  thanks for the PR 

Could you instead of adding a separate file for FAQ, mention it somewhere in the README.rst ? 

Also for now don't create a separate FAQ section at the README. Instead mention running few importers in the setup section itself .

Do fix the DCO check too :)  They have nice instructions at  https://github.com/nexB/vulnerablecode/pull/283/checks?check_run_id=1435132472 .

**Comment by tushar912** [comment]
@sbs2001 I have made the changes . I tried to fix DCO but I am unable to fix it even after multiple times .

**Comment by tushar912** [comment]
I think <code>git commit --amend --signoff</code> sign off only latest commit

**Comment by tushar912** [comment]
@sbs2001 I did rebase so it is passing the test now.

**Review by sbs2001 — COMMENTED** [review]
One last nit :

How about rephrasing  `In fact it is suggested
to run only a few small importers via `  to `To quickly get started with some data run : ` ?

**Comment by tushar912** [comment]
I have made the changes

**Review by sbs2001 — APPROVED** [review]

**Pull request merged**
