### PR TITLE
Added type checking in CI

### PR DESCRIPTION
**Pull request by abhishak3**
Issue #226 

- added type checking in CI
- updated requirements-dev.txt to include mypy==0.931

Signed-off-by: Abhishek <abhishek.pandey.3237@gmail.com>

### CODE REVIEW

**Comment by Hritik14** [comment]
@abhishak3 ping! failing tests

**Comment by abhishak3** [comment]
@Hritik14 those errors were caused by mypy because mypy was able to find the modules we were importing, but no corresponding type hints. So, we need to suppress these errors using the `--ignore-missing-imports` flag which is what I did in the latest commit.
For more info, refer [here](https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-library-stubs-or-py-typed-marker).

**Comment by abhishak3** [comment]
@Hritik14 can you please approve my pr?

**Comment by pombredanne** [comment]
@abhishak3 I cannot merge this unless this is passing all the tests correctly without first having to change all the code.

**Comment by abhishak3** [comment]
any suggestions on how to do this ?

**Comment by pombredanne** [comment]
@abhishak3 I have not the start of an idea.

**Pull request closed without merging**
