### PR TITLE
Begin work on combining affected and fixed by packages #1287

### PR DESCRIPTION
**Pull request by johnmhoran**
Reference: https://github.com/nexB/vulnerablecode/issues/1287

### CODE REVIEW

**Comment by TG1999** [comment]
@johnmhoran is this PR ready for review ?

**Comment by johnmhoran** [comment]
Thanks for the question @TG1999.  No, this draft PR is nowhere close to being ready for review.  I started this work on the VCIO Vulnerability UI/API back in October when my Package UI/API PR was ready and awaiting comments, but this work incorporates that work and thus I hit a roadblock early on and stopped because the Package PR lingered for a while.  That roadblock is now gone.  ;-)

This Vulnerability work also involves the "bad" data issues (e.g., duplicate PURLs), since combining the affected by tab and fixed by tab will currently include all the duplicate PURLs (and might also involve their respective but possibly different vulnerabilities).  However, I'm inclined to go ahead despite the data issue and see what the combined affected by/fixed by tabs look like.  I expect that for each set of duplicate PURLs we'll have 2 rows, not 1, which might confuse or even put off users but seems unavoidable while the data issue persists.

**Comment by TG1999** [comment]
@johnmhoran  what's status on this PR ?

**Comment by johnmhoran** [comment]
Thanks @TG1999 -- I'm glad you asked.  As I mentioned when we discussed this draft PR on last Tuesday's weekly vulnerablecode jit.si, this draft PR is essentially a placeholder and the underlying work has not begun.  My understanding from @pombredanne 's comments during that call was that there are significant changes coming to the related data/model structure and the work on this issue #1320 needs to wait for those changes.

If that is not the case and I can start work on this issue, please let me know.  I have a handful of PRs awaiting review on several other projects and meanwhile have time to work on something new, and this might be a good issue to focus on.  

Note that @pombredanne opened a new issue during last week's jit.si that covers both the API and UI and refers to the issue underlying this PR -- [Do not mix unrelated affected and fixed packages #1508](https://github.com/nexB/vulnerablecode/issues/1508) .

**Comment by johnmhoran** [comment]
Closing this draft PR, and replacing but temporarily keeping its related branch `1287-combine-affected-fixed-tabs` for use as a reference, to be deleted when no longer needed.  I'll open a new branch to resume my work matching affected and fixed-by packages -- issue #1287, and referenced recently in #1508 -- and will open a new PR when ready.

**Comment by johnmhoran** [comment]
Closing this draft PR, and replacing but temporarily keeping its related branch `1287-combine-affected-fixed-tabs` for use as a reference, to be deleted when no longer needed. I'll open a new branch to resume my work matching affected and fixed-by packages -- issue #1287, and referenced recently in #1508 -- and will open a new PR when ready.

**Pull request closed without merging**
