### PR TITLE
Issue #151 Removed call to circl api

### PR DESCRIPTION
**Pull request by aniket-chowdhury**

### CODE REVIEW

**Comment by haikoschol** [comment]
@aniket-chowdhury Thanks for this contribution. Please make sure all your commits are signed off and take into account [my comment on the ticket](https://github.com/nexB/vulnerablecode/issues/151#issuecomment-599058660).

**Comment by haikoschol** [comment]
@aniket-chowdhury are you still interested in finishing this pull request?

**Comment by aniket-chowdhury** [comment]
Yeah. I still am.

**Comment by haikoschol** [comment]
> 
> 
> @haikoschol
> Yeah. I still am.

Do you need help with fixing the issues or are you just busy and haven't gotten to it yet?

**Comment by aniket-chowdhury** [comment]
I think it would break functionality. Could you elaborate more on the issue.

**Comment by haikoschol** [comment]
> I think it would break functionality. Could you elaborate more on the issue.

I already did elaborate on the ticket [here](https://github.com/nexB/vulnerablecode/issues/151#issuecomment-599058660).

We want to remove this route completely from the application, not just the call to the other API.

The other issue with your pull request is [the failing DCO check](https://github.com/nexB/vulnerablecode/pull/159/checks). You can find documentation on how to fix that [here](https://help.github.com/en/github/committing-changes-to-your-project/changing-a-commit-message).

**Pull request closed without merging**
