### PR TITLE
Added license_url

### PR DESCRIPTION
**Pull request by sdivyanshu90**
Fixes: #656
Changes:
- Added the license_url

### CODE REVIEW

**Comment by sdivyanshu90** [comment]
Hi @TG1999 and @pombredanne, could you review my pull request and provide feedback? Thanks!

**Comment by TG1999** [comment]
@sdivyanshu90 tests are failing, can you check it once ?

**Comment by TG1999** [comment]
And also you may need to re-write your commit message, your commit message needs to be imperative, have a look on this https://cbea.ms/git-commit/

**Comment by sdivyanshu90** [comment]
> @sdivyanshu90 thanks! tests are failing, can you check it once ?

Yes, I am investigating why the tests are failing.

> And also you may need to re-write your commit message, your commit message needs to be imperative, have a look on this https://cbea.ms/git-commit/

Sure, I will make my commit message imperative.

**Comment by sdivyanshu90** [comment]
Now it passes all the tests, and I have changed the commit message to be imperative. @TG1999, could you please re-review it?

**Comment by TG1999** [comment]
@sdivyanshu90 please resolve conflicts!

**Comment by sdivyanshu90** [comment]
@TG1999, I have resolved the conflicts. Could you please review it?

**Pull request closed without merging**
