### PR TITLE
Use get or create to reduce the number of objects created

### LINKED ISSUE #40: Replace objects.create with objects.update_or_create.
Replace objects.create with objects.update_or_create along with new tests regarding this.

### PR DESCRIPTION
**Pull request by singh1114**
Fixes #40

Signed-off-by: Ranvir Singh <ranvir.singh1114@gmail.com>

### CODE REVIEW

**Comment by singh1114** [comment]
@pombredanne Did that!

**Comment by singh1114** [comment]
> This is looking good otherwise, though do you think there could be a unit test that would show that there were issues with a bare create before?

I think we already had tests which specified the number of objects being created. Reducing the count in the tests itself will account for the same thing.

**Comment by haikoschol** [comment]
@singh1114 I still don't see how this PR fixes #40. Did you mean to reference #28, which is about duplicate data?

Either way, I think the import process needs to be redesigned (and called "import" instead of "data dump", but let's not bikeshed about that just now :). Apart from issues #28 and #40, the current process is also not scalable, already way too slow, and it will only get worse by using either `get_or_create` or `create_or_update`.

We should distinguish between importing historical data once, when an instance of vulnerablecode is provisioned, and continuously importing updates from vulnerability sources. Otherwise the time for the latter process will continue to grow with the amount of data.

**Comment by singh1114** [comment]
@haikoschol Sorry meant to refer #28 for the duplicate data. #40 doesn't seem to be correct and is a duplicate to #28 

Agreed with your view of differentiating both the procedures.

For improving the speed of the dump, we can use `bulk_create` (and it would be good to call it dump if we use that but handling duplicates in that case will be more difficult).

Anyway, we will have to make sure the data in the DB is unique.

**Comment by haikoschol** [comment]
@singh1114 I agree that we should use `bulk_create`, at least for the initial import, but probably for updates as well.

However, I don't think that #40 is a duplicate of #28. I suggest we continue the discussion what #40 is about directly on the issue instead of this PR.

**Comment by pombredanne** [comment]
At this stage and based on the discussions here and the changes that were applied, I think it is best to close and continue the discussion in #40

**Pull request closed without merging**
