### PR TITLE
Sending API key using email template

### PR DESCRIPTION
**Pull request by ziadhany**
[#1003](https://github.com/nexB/vulnerablecode/issues/1003)
Signed-off-by: ziadhany <ziadhany2016@gmail.com>

### CODE REVIEW

**Comment by ziadhany** [comment]
What does email look like on all devices
image
image
image

**Comment by TG1999** [comment]
@ziadhany please provide screenshots of how this email looked previously without your changes and with your changes

**Comment by ziadhany** [comment]
> @ziadhany please provide screenshots of how this email looked previously without your changes and with your changes

image

**Comment by ziadhany** [comment]
> > @ziadhany please provide screenshots of how this email looked previously without your changes and with your changes
> 
this is without my changes
> image

**Comment by pombredanne** [comment]
It really looks good, but I am still pondering whether a plain text would not best. I am always suspicious of HTML email with links.

**Comment by ziadhany** [comment]
> It really looks good, but I am still pondering whether a plain text would not best. I am always suspicious of HTML email with links.

I think we can send both html and text/plain ( if you don't mind ) and let the user choose what he wants

**Pull request closed without merging**
