### PR TITLE
Add support for severity range

### PR DESCRIPTION
**Pull request by ziadhany**
issue: #889

### CODE REVIEW

**Review by pombredanne — APPROVED** [review]
Looks good to me. Thank you!
can you add a screenshot to help visualize where this shows up?
@DennisClark your review is much welcomed

**Comment by DennisClark** [comment]
@ziadhany   one or more screenshots would be very helpful, thanks

**Comment by ziadhany** [comment]
> @ziadhany one or more screenshots would be very helpful, thanks

ok sure 

Screenshot 2023-04-21 at 23-31-25 VulnerableCode Vulnerability Details - VCID-12mr-dt14-aaah

Screenshot 2023-04-21 at 23-34-50 VulnerableCode Vulnerability Details - VCID-zmd4-akdr-aaab

image

and this if we have just one severity ( no severity range ) 
image

**Comment by DennisClark** [comment]
@ziadhany   looks good to me 👍

**Pull request merged**
