### PR TITLE
Increase display width #1299

### PR DESCRIPTION
**Pull request by johnmhoran**
Reference: https://github.com/nexB/vulnerablecode/issues/1299

### CODE REVIEW

**Comment by johnmhoran** [comment]
@DennisClark Not sure who needs or wants to review this PR, but I think as discussed during today's jit.si that the changes increase the VCIO display width to that currently used by ScanCode.io.  Comments/questions are welcome.

**Comment by DennisClark** [comment]
@johnmhoran    Based on the screenshots you posted to me earlier, the changes are fine with me, but I guess someone qualified should review the actual code -- perhaps @TG1999  ?

**Review by keshav-space — COMMENTED** [review]
@johnmhoran Why not use the entire 100% of the available width?

| Width 100%  |
| ------------- |
| Screenshot from 2024-05-22 01-14-51 |

**Comment by johnmhoran** [comment]
Thanks @keshav-space.  BTW, did you change the 2 px settings I changed to `100%` to achieve your results (in case that's what the final decision is)?  

Re why not?  I understood the goal was to imitate the display of ScanCode.io.  If the decisionmakers want something different, that's fine -- waiting for instructions....  (Having some white space on left and right looks better to me, fwiw.)

**Comment by DennisClark** [comment]
@johnmhoran  @keshav-space    the `100%"  approach is even better, I think.  Please give it a try.

**Comment by johnmhoran** [comment]
Thanks @DennisClark, will do.

**Comment by johnmhoran** [comment]
@keshav-space @DennisClark    Pushing this shortly:

SCIO-like width:

image


100% width:

image

**Comment by johnmhoran** [comment]
Pushed the 100% update.

**Comment by keshav-space** [comment]
@johnmhoran running your changes locally, I'm not getting the full width. 🤔

Screenshot from 2024-05-22 20-52-42

**Comment by johnmhoran** [comment]
@keshav-space Thanks.  Although I had the full 100% width locally yesterday (thus the screenshot above), atm mine is also narrow, somehow being limited to 865.63px.  Looking I don't see where that comes from -- maybe some flex-related CSS setting?  Do you have any suggestions?  Meanwhile I'll see what I can discover.

image

**Comment by keshav-space** [comment]
@johnmhoran this is what worked for me locally.

```css
.container.max-desktop-width {
    width: 100%;
    max-width: 100%;
}
```
```css
@media screen and (min-width: 1024px) {
    .footer {
        width: 100%;
    }
}
```

**Comment by johnmhoran** [comment]
@keshav-space Adding the missing `width` to `.container.max-desktop-width` works for me as well -- thank you.  Weird that I had the full width yesterday w/o that setting, and there was previously no `width` setting for that CSS.  🤔   Will commit and push shortly.

image

**Review by keshav-space — APPROVED** [review]
@johnmhoran LGTM!
IMO, the package and vulnerability search should be modified to take up approximately 60-70% of the width, that might look better. We can track this in a separate issue.

**Comment by keshav-space** [comment]
Merging!

**Pull request merged**
