### PR TITLE
use https.ok from HTTP package

### PR DESCRIPTION
**Pull request by thebigbone**

### CODE REVIEW

**Comment by pombredanne** [comment]
Thank you. Can you check the style check failures? https://github.com/nexB/vulnerablecode/actions/runs/8490816624/job/23265445454?pr=1450#step:6:671

**Comment by thebigbone** [comment]
All tests passed!

**Review by TG1999 — APPROVED** [review]
LGTM!

**Review by pombredanne — APPROVED** [review]
Thanks!

**Pull request merged**
