### PR TITLE
https://github.com/nexB/vulnerablecode/issues/725

### PR DESCRIPTION
**Pull request by markrouz**

### CODE REVIEW

**Comment by TG1999** [comment]
Hey @markrouz , thanks for this, can you add some tests and also sign off the commit message, DCO is failing

**Comment by markrouz** [comment]
> Hey @markrouz , thanks for this, can you add some tests and also sign off the commit, DCO is failing

@TG1999 thanks for pointing this out. Done

**Review by TG1999 — APPROVED** [review]
LGTM! @pombredanne please have a look here once

**Review by pombredanne — APPROVED** [review]
LGTM :+1: Thanks you ++

**Pull request merged**
