### PR TITLE
Feature implement linked commits

### PR DESCRIPTION
**Pull request by JafarAkhondali**
Hello, first-time contribution here.
I had to adjust `Improver` model  to support custom improver, as the previous method assumes improvers will return always an advisory data (If I understood correctly).
It's also safe to run the command multiple time, as it uses a one-to-one relation with constrain checking.
The `chain_urls` field might be filled in next PR to record usage of multiple links to reach commit(s).

### CODE REVIEW

**Comment by pombredanne** [comment]
Thanks!
We use DCO signoffs so you may need to amend your commit messages to make the DCO bot happy!

**Comment by pombredanne** [comment]
> I had to adjust Improver model to support custom improver, as the previous method assumes improvers will return always an advisory data (If I understood correctly).

That's something that was in the plan. Eventually an improver should be able to do anything it likes to do and the initial limitation with some "advisory" needed to be replaced.

**Comment by JafarAkhondali** [comment]
I've signed the commits, so DCO should be happy now :)

**Comment by JafarAkhondali** [comment]
@pombredanne There were some issues with formats, I fixed them and rebased the commits.

**Comment by TG1999** [comment]
@JafarAkhondali please rebase the PR

**Comment by pombredanne** [comment]
@JafarAkhondali I am closing this for now as this is not finished/tested and cannot be merged yet. We are tracking the main "reachability" feature in:
- https://github.com/nexB/vulnerablecode/issues/1313

**Pull request closed without merging**
