### PR TITLE
Improve Ubuntu OVAL importer

### PR DESCRIPTION
**Pull request by pombredanne**
There are a few issues with the Ubuntu Oval importer that was stuck.
This resolves some of these issues:
- Do not fail when there is a version range that cannot be parsed as a RangeSpecifier(). 
- Improve error handling
- Add simple logging using print statements to help monitor import progress
- Also apply minor code formatting.
- I also added a code comment about the Etag handling which IMHO are more problematic than helpful at this stage, especially when there is a failure during import. See also #321

Signed-off-by: Philippe Ombredanne <pombredanne@nexb.com>

### CODE REVIEW

**Comment by pombredanne** [comment]
Note that I will need to add tests before we can merge and also the Ubuntu importer still does NOT complete after running for a day.

**Comment by sbs2001** [comment]
@pombredanne  Any luck with completing the whole import ?

**Comment by pombredanne** [comment]
> @pombredanne Any luck with completing the whole import ?

@sbs2001 I stopped it after several hours and about ~8000 completed (e.g. after the first archive)

**Comment by sbs2001** [comment]
I'm running the import at https://github.com/sbs2001/vulnerablecode/runs/1792912071?check_suite_focus=true

**Comment by sbs2001** [comment]
@pombredanne  I think we should ditch pycodestyle and use black for both checking + formatting like https://github.com/nexB/skeleton/issues/13#issuecomment-722486247

**Pull request merged**
