### PR TITLE
Resolves #380: Added severity in the view at http://127.0.0.1:8000/vulnerabilities/<vulnerability_id>

### LINKED ISSUE #380: Display severities in the vulnerability view
In the view at http://127.0.0.1:8000/vulnerabilities/<vulnerability_id> we need to display the severity obtained from various data sources.

The severity must be nested inside the reference to show the connection.

### PR DESCRIPTION
**Pull request by Pushpit07**
Added severity in the view at http://127.0.0.1:8000/vulnerabilities/<vulnerability_id> by adding the severity to the context sent by the view and referencing it in the html page

### CODE REVIEW

**Comment by sbs2001** [comment]
Could you post a screenshot/video/gif  ?

**Comment by Pushpit07** [comment]
> Could you post a screenshot/video/gif ?

Screenshot 2021-03-18 at 12 42 55

**Comment by sbs2001** [comment]
I've commented in https://github.com/nexB/vulnerablecode/issues/380, we want both fields of the severity. 

Also add signoff to your commits to pass the dco check

**Comment by Pushpit07** [comment]
Done!

Screenshot 2021-03-18 at 15 22 31


Screenshot 2021-03-18 at 15 22 14

**Comment by sbs2001** [comment]
@Pushpit07 could you rebase this properly ? Also a reference can contain multiple severities, I'm wondering how that would look like on the UI side ? Ideas appreciated there :)

**Comment by Pushpit07** [comment]
Seems like the severities aren't being returned as a list of values. There's only one value being returned. That's why when I tried to loop over the severities, it separated the characters instead of the words 

Screenshot 2021-03-19 at 08 35 33
Screenshot 2021-03-19 at 08 35 41

**Comment by Pushpit07** [comment]
I tried to loop of a list to debug and in that case the output was as expected
Screenshot 2021-03-19 at 08 25 47

**Comment by Pushpit07** [comment]
Rebased it properly. I've made changes to 2 files only

**Comment by Pushpit07** [comment]
Also, I messed up the process a little this time. Sorry for that. Won't happen in the future

**Comment by sbs2001** [comment]
@Pushpit07  the rebase is messed up, I'm seeing 18 commits now. You could open a new PR on branch created off from latest main 

Regarding https://github.com/nexB/vulnerablecode/pull/385#issuecomment-802512838 

you could run the nvd importer to get some real examples of multiple severity scores. 
I don't understand what you are trying to convey in the screenshot ? Does the reference have 3 severity systems called `good, better, best` ?  If yes, then they will three distinct values

**Pull request closed without merging**
