### PR TITLE
Add support for setting Postgres port via env var

### PR DESCRIPTION
**Pull request by kipz**

### CODE REVIEW

**Review by sbs2001 — APPROVED** [review]
Thanks.  I'm curious how you guys are planning to use vulnerablecode at http://atomist.com/  :)

**Comment by sbs2001** [comment]
@kipz  could you fix the dco and we can merge then

**Comment by kipz** [comment]
> Thanks. I'm curious how you guys are planning to use vulnerablecode at http://atomist.com/ :)

Just playing at the moment, but we like the approach for sure! 

By the way, have you seen any open-access hosted versions out there in the wild yet?

**Comment by sbs2001** [comment]
@kipz  

no hosted versions atm ):  but it's a high priority on our roadmap.

In any case, let us know if you have any feature requests, bugs etc.

**Comment by pombredanne** [comment]
@kipz re:

> By the way, have you seen any open-access hosted versions out there in the wild yet?

Yes that's high on the todo list to help seed things up too faster

**Comment by kipz** [comment]
@pombredanne @sbs2001 FWIW - I'm playing with an instance over here: https://vulnerablecode.atomist.com/

**Comment by pombredanne** [comment]
@kipz this is great!

**Pull request merged**
