### PR TITLE
Add license_url for GitHub Importer

### PR DESCRIPTION
**Pull request by Akash-Kumar-Sen**
- Fixes https://github.com/nexB/vulnerablecode/issues/656
- Only changed file : https://github.com/nexB/vulnerablecode/blob/main/vulnerabilities/importers/github.py
- Line no : 165

### CODE REVIEW

**Comment by TG1999** [comment]
@Akash-Kumar-Sen sign off is missing in the commit message.

**Comment by Akash-Kumar-Sen** [comment]
Okay I will add that @TG1999

**Comment by TG1999** [comment]
Gentle ping @Akash-Kumar-Sen

**Comment by Akash-Kumar-Sen** [comment]
Adding it today

**Comment by TG1999** [comment]
Gentle ping @Akash-Kumar-Sen , we want to merge this, please provide your sign-off

**Comment by pombredanne** [comment]
@Akash-Kumar-Sen ping

**Comment by TG1999** [comment]
Hey, thank you very much but I am closing this for lack of activity.

**Pull request closed without merging**
