### PR TITLE
Migrate apache tomcat importer

### PR DESCRIPTION
**Pull request by johnmhoran**

### CODE REVIEW

**Comment by TG1999** [comment]
@johnmhoran please provide importer and improver logs for this importer.

**Comment by johnmhoran** [comment]
@TG1999 What are `importer and improver logs`?  I don't think I did this for the archlinux, apache_httpd, apache_kafka or postgresql importers.

**Comment by TG1999** [comment]
@johnmhoran please run the importer you have migrated and also run the improver over the data you migrated, and show the logs that you got by running the importer and the improver.

**Comment by johnmhoran** [comment]
Thanks @TG1999 .  I'll do a rebase/--force first.  Shall I paste the terminal results of running the importer/improver as a comment here?

**Comment by TG1999** [comment]
@johnmhoran you can attach a txt file in comments here

**Comment by johnmhoran** [comment]
Excellent -- will do.  👍

**Comment by johnmhoran** [comment]
@TG1999 After running the import command I received the following error:

```
(venv) Fri Jan 20, 2023 11:34 AM  /home/jmh/dev/nexb/vulnerablecode jmh (970-migrate-apache-tomcat-importer)
$ ./manage.py import vulnerabilities.importers.apache_tomcat.ApacheTomcatImporter
Importing data using vulnerabilities.importers.apache_tomcat.ApacheTomcatImporter
Traceback (most recent call last):
  File "/home/jmh/dev/nexb/vulnerablecode/vulnerabilities/management/commands/import.py", line 60, in import_data
    ImportRunner(importer).run()
  File "/home/jmh/dev/nexb/vulnerablecode/vulnerabilities/import_runner.py", line 44, in run
    count = process_advisories(advisory_datas=advisory_datas, importer_name=importer_name)
  File "/home/jmh/dev/nexb/vulnerablecode/vulnerabilities/import_runner.py", line 57, in process_advisories
    data.summary = data.summary.replace("\x00", "\uFFFD")
AttributeError: 'generator' object has no attribute 'summary'
Failed to run importer vulnerabilities.importers.apache_tomcat.ApacheTomcatImporter. Continuing...
CommandError: 1 failed!: vulnerabilities.importers.apache_tomcat.ApacheTomcatImporter

(venv) Fri Jan 20, 2023 11:39 AM  /home/jmh/dev/nexb/vulnerablecode jmh (970-migrate-apache-tomcat-importer)
$
```

**Comment by johnmhoran** [comment]
@TG1999 I'm attaching `vcio-apache_tomcat-import-and-improve-2023-01-20.txt` containing the terminal output from
 running the import and improve steps.  Please note that while both were successful, the import step output included this item:

```
'RC1' is not a valid SemverVersion InvalidVersion("'RC1' is not a valid <class 'univers.versions.SemverVersion'>")
```

[vcio-apache_tomcat-import-and-improve-2023-01-20.txt](https://github.com/nexB/vulnerablecode/files/10470546/vcio-apache_tomcat-import-and-improve-2023-01-20.txt)

**Comment by TG1999** [comment]
LGTM!

**Review by TG1999 — APPROVED** [review]

**Pull request merged**
