### PR TITLE
Update README.rst

### PR DESCRIPTION
**Pull request by InLaw**
nix-shell for flakes

### CODE REVIEW

**Comment by sbs2001** [comment]
@rolfschr  I guess this has something to do with your changes ?

**Comment by InLaw** [comment]
black needs e.g. a patch >19.3b0

**Comment by rolfschr** [comment]
The CI should work after https://github.com/nexB/vulnerablecode/pull/370 is merged.

**Comment by sbs2001** [comment]
@rolfschr  Thanks for the quick fix , @InLaw  could you add a signoff, so we can  merge this and #370 PR ?

**Pull request merged**
