### PR TITLE
Doc maintenance

### PR DESCRIPTION
**Pull request by Sohima**

### CODE REVIEW

**Comment by Sohima** [comment]
@nexB

**Comment by pombredanne** [comment]
@Sohima Thank for the update... I think the standard for a signoff would be something like this with angular brackets and should match your Github details:
```
Signed-off-by: Firstname Lastname <email@example.com>
```

**Comment by TG1999** [comment]
@Sohima gentle ping! Please add your sign-off so we can merge this PR.

**Comment by pombredanne** [comment]
gentle ping before we close this.

**Comment by pombredanne** [comment]
@Sohima I am closing because we are missing a DCO signoff... please reopen when you add it. Thank you!

**Pull request closed without merging**
