### PR TITLE
Add tests for improver

### PR DESCRIPTION
**Pull request by Hritik14**
fixes: https://github.com/nexB/vulnerablecode/issues/612
Signed-off-by: Hritik Vijay <hritikxx8@gmail.com>

### CODE REVIEW

**Comment by TG1999** [comment]
@Hritik14 tests are failing , please re-run your tests once.

**Comment by Hritik14** [comment]
@TG1999  This does not make sense.
Failed: https://github.com/nexB/vulnerablecode/actions/runs/4941002519/attempts/1
Passed: https://github.com/nexB/vulnerablecode/actions/runs/4941002519/attempts/2

Only re-running the jobs made the tests pass without any code change.

**Comment by TG1999** [comment]
@Hritik14 it seems to me it's a Heisenbug ?

**Comment by Hritik14** [comment]
@TG1999 Possibly

**Pull request merged**
